// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

String getSdkVersion() => RustLib.instance.api.crateApiSimpleGetSdkVersion();

List<BuildingDto> getAllBuildings() =>
    RustLib.instance.api.crateApiSimpleGetAllBuildings();

int calculateWeekNumber({String? termStartDate}) => RustLib.instance.api
    .crateApiSimpleCalculateWeekNumber(termStartDate: termStartDate);

class BuildingDto {
  final String key;
  final String name;
  final String campusName;
  final int campusId;
  final List<String> defaultFloors;

  const BuildingDto({
    required this.key,
    required this.name,
    required this.campusName,
    required this.campusId,
    required this.defaultFloors,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      name.hashCode ^
      campusName.hashCode ^
      campusId.hashCode ^
      defaultFloors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuildingDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          name == other.name &&
          campusName == other.campusName &&
          campusId == other.campusId &&
          defaultFloors == other.defaultFloors;
}
